#define yyFlexLexer contextop_yyFlexLexer
#define yywrap contextop_yywrap

/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /cvs/intense/intense/libintense/src/ContextOpLexer.cpp,v 1.10 2004/08/10 01:59:39 pws Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5



/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <iostream>
using namespace std;

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	istream* yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};


/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer



static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
#define yytext_ptr yytext
#define YY_INTERACTIVE

#include "correct_FlexLexer.h"
int yyFlexLexer::yylex()
	{
	LexerError( "yyFlexLexer::yylex invoked but %option yyclass used" );
	return 0;
	}

#define YY_DECL int intense::ContextOpLexer::yylex()


/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 46
#define YY_END_OF_BUFFER 47
static yyconst short int yy_accept[129] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,   47,   34,
       45,    1,    1,   26,   27,   44,   37,   34,   34,   34,
       46,   40,   41,   42,   43,   36,   35,   20,   16,   13,
       11,   10,   12,   15,   14,   18,   17,   19,   46,   24,
       21,   21,   22,   23,   30,   29,   46,   34,   45,   34,
       32,    1,    1,   25,   38,    0,    0,   34,   33,   33,
       34,   34,   34,   34,   31,   20,   18,   19,    3,    3,
       21,   29,   28,   39,    0,    0,    0,   31,   34,    0,
        2,   32,   34,    0,   34,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    6,    6,    4,    5,    0,    0,

        0,    0,    0,    0,    7,    7,    4,    5,    0,    0,
        0,    0,    0,    0,    8,    8,    4,    5,    0,    0,
        0,    0,    0,    0,    9,    4,    5,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    2,    3,    4,    5,
        6,    7,    8,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    9,    1,   10,   11,    1,    1,    1,    1,    1,
        1,    1,   12,    1,   13,   14,   15,   16,   17,   18,
       19,   17,   20,   17,   21,   22,   22,   23,    1,   24,
        1,   25,    1,    1,   26,   27,   28,   29,   30,   31,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,   32,    1,    1,    1,    1,    1,
       33,   34,   35,   36,    1,    1,   26,   27,   28,   29,

       30,   31,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,   37,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[38] =
    {   0,
        1,    2,    2,    3,    4,    2,    2,    3,    5,    3,
        6,    7,    8,    1,    9,   10,   10,   10,   10,   10,
       10,   10,   11,    6,    6,   12,   12,   12,   12,   12,
       12,    1,    6,    2,    6,    5,    5
    } ;

static yyconst short int yy_base[147] =
    {   0,
        0,    0,   37,    0,   71,   91,  114,    0,  272,  151,
        0,   78,   80,  176,  719,  719,   77,   82,  188,  210,
      719,  719,  719,  719,  719,    0,    0,    0,  719,  719,
      719,  719,  719,  719,  719,    0,  719,  218,  152,  719,
       98,  104,  719,  719,  719,  237,    0,    0,    0,  153,
      719,  239,    0,  719,  162,  248,  265,  288,  133,  719,
      310,    0,  322,    0,  719,    0,    0,    0,  719,  143,
      246,  248,    0,  719,    0,   65,    0,  719,    0,  344,
      719,    0,  363,   79,  370,  385,    0,  401,  415,  231,
      125,    0,  433,  440,  330,    0,    0,    0,  455,    0,

      471,  485,  325,   81,  377,    0,    0,    0,  501,    0,
      517,  531,  394,   80,  447,    0,    0,    0,  547,  558,
      572,  586,  464,   74,  719,  719,  719,  719,  617,  629,
      634,  644,  656,  664,  675,  678,  681,  684,   88,  690,
      691,  694,  697,  700,  703,  706
    } ;

static yyconst short int yy_def[147] =
    {   0,
      128,    1,  128,    3,  129,  129,  128,    7,  128,  128,
      130,  128,  130,  128,  128,  128,  131,  132,  128,   19,
      128,  128,  128,  128,  128,  130,  130,  133,  128,  128,
      128,  128,  128,  128,  128,  134,  128,  133,  135,  128,
      128,  128,  128,  128,  128,  128,  136,   10,  130,  132,
      128,  128,   13,  128,  128,   19,   56,  128,  132,  128,
      132,   19,   61,   20,  128,  133,  134,   38,  128,  137,
      128,  128,  138,  128,  139,  140,   57,  128,   58,   58,
      128,   80,   19,  140,   83,  128,  141,  141,  128,  141,
      141,  136,   56,   93,  142,  142,  142,  142,  128,  143,

      143,  128,  143,  143,  144,  144,  144,  144,  128,  145,
      145,  128,  145,  145,  146,  146,  146,  146,  128,  119,
      120,  128,  120,  120,  128,  128,  128,    0,  128,  128,
      128,  128,  128,  128,  128,  128,  128,  128,  128,  128,
      128,  128,  128,  128,  128,  128
    } ;

static yyconst short int yy_nxt[757] =
    {   0,
       10,   11,   11,   12,   12,   11,   11,   12,   13,   14,
       15,   16,   17,   10,   18,   19,   20,   20,   20,   20,
       20,   20,   21,   22,   23,   10,   10,   10,   10,   10,
       10,   10,   24,   11,   25,   26,   27,   28,   29,   30,
       31,   32,   33,   34,   35,   36,   37,   36,   36,   36,
       28,   28,   38,   38,   38,   38,   38,   38,   38,   36,
       36,   36,   28,   28,   28,   28,   28,   28,   28,   36,
       39,   36,   36,   36,   41,   42,   84,   84,   41,   41,
       43,   52,   52,   52,   52,   52,   52,   52,   53,   55,
      128,  128,   56,   44,   41,   42,   58,   93,   41,   41,

       43,   71,   71,  126,   51,   71,   71,   71,   71,  117,
      107,   71,   71,   44,   45,   45,   45,   46,   46,   45,
       45,   46,   46,   45,   45,   45,   45,   45,   45,   47,
       47,   47,   47,   47,   47,   47,   45,   45,   45,   47,
       47,   47,   47,   47,   47,   45,   45,   45,   45,   45,
       45,   48,   49,   49,   97,   51,   49,   49,   86,   49,
       88,   89,   90,   91,   48,   50,   50,   50,   50,   50,
       50,   50,   50,   51,   74,   51,   48,   48,   48,   48,
       48,   48,   48,   70,   49,   54,   49,   49,   59,   60,
       60,   60,   60,   60,   60,   60,   60,   60,   60,   60,

       60,   61,   59,   62,   62,   62,   62,   62,   62,   62,
       51,   60,   60,   59,   59,   59,   59,   63,   59,   59,
       60,   60,   60,   60,   60,   64,   64,   64,   64,   64,
       64,   64,   65,   68,   68,   68,   68,   68,   68,   68,
       72,   72,   52,   52,   72,   72,   52,   52,   60,   71,
       71,   72,   72,   71,   71,   72,   72,   97,   97,   97,
       97,   75,   60,   56,   56,   56,   56,   56,   56,   56,
      128,  128,  128,   60,   60,   60,   60,   76,   60,   60,
       77,   77,   77,   77,   77,   77,   77,   78,   79,   80,
       80,   80,   81,   80,   80,   80,   80,   80,   80,   80,

       80,   79,   79,   79,   79,   79,   79,   79,   79,   79,
       82,   80,   80,   79,   79,   79,   79,   79,   79,   79,
       80,   80,   80,   80,   80,   83,   83,   83,   83,   83,
       83,   83,   51,   84,   84,  128,  128,   85,   85,   85,
       85,   85,   85,   85,   80,   99,  128,  101,  102,  103,
      104,  107,  107,  107,  107,  128,  128,   80,   80,   80,
       80,   80,   80,   80,   80,   80,   80,  128,  128,   80,
       80,   80,   80,   80,   80,   80,   50,  128,   83,   83,
       83,   83,   83,   83,   83,   85,   85,   85,   85,   85,
       85,   85,  109,  128,  111,  112,  113,  114,  128,   50,

       95,   96,   96,   96,   96,   97,   97,  128,  128,  128,
       97,   97,   97,   97,   96,   96,   97,  128,   97,   97,
      117,  117,  117,  117,  128,  128,  128,   97,  128,   97,
       98,   98,   98,   98,   98,   98,   98,  128,  128,  128,
       97,   96,   97,   96,   97,   96,  128,  128,   93,   93,
       93,   93,   93,   93,   93,   94,   94,   94,   94,   94,
       94,   94,  119,  128,  121,  122,  123,  124,  128,  128,
      105,  106,  106,  106,  106,  107,  107,  128,  128,  128,
      107,  107,  107,  107,  106,  106,  107,  128,  107,  107,
      126,  126,  126,  126,  128,  128,  128,  107,  128,  107,

      108,  108,  108,  108,  108,  108,  108,  128,  128,  128,
      107,  106,  107,  106,  107,  106,  115,  116,  116,  116,
      116,  117,  117,  128,  128,  128,  117,  117,  117,  117,
      116,  116,  117,  128,  117,  117,  128,  128,  128,  128,
      128,  128,  128,  117,  128,  117,  118,  118,  118,  118,
      118,  118,  118,  128,  128,  128,  117,  116,  117,  116,
      117,  116,  125,  125,  125,  125,  125,  126,  126,  128,
      128,  128,  126,  126,  126,  126,  125,  125,  125,  125,
      128,  128,  128,  125,  125,  125,  125,  126,  128,  126,
      126,  128,  128,  128,  128,  128,  128,  128,  126,  128,

      126,  127,  127,  127,  127,  127,  127,  127,  128,  128,
      128,  126,  125,  126,  125,  126,  125,   40,   40,   40,
       40,   40,   40,   40,   40,   40,   40,   40,   40,   49,
       49,  128,  128,   49,  128,  128,  128,  128,  128,  128,
       49,   57,  128,   57,   50,  128,  128,  128,  128,  128,
      128,  128,   50,   50,   50,   50,   66,  128,  128,  128,
      128,  128,  128,  128,   66,   66,  128,   66,   67,   67,
       67,   67,  128,  128,   67,   69,   69,   69,  128,   69,
       69,   69,   69,   69,   69,   69,   69,   73,  128,   73,
       87,  128,   87,   92,  128,   92,   94,   94,  128,   94,

       96,  128,   96,  100,  128,  100,  106,  128,  106,  110,
      128,  110,  116,  128,  116,  120,  128,  120,    9,  128,
      128,  128,  128,  128,  128,  128,  128,  128,  128,  128,
      128,  128,  128,  128,  128,  128,  128,  128,  128,  128,
      128,  128,  128,  128,  128,  128,  128,  128,  128,  128,
      128,  128,  128,  128,  128,  128
    } ;

static yyconst short int yy_chk[757] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    5,    5,   76,   76,    5,    5,
        5,   12,   12,   13,   13,   12,   12,   13,   13,   17,
       84,   84,   17,    5,    6,    6,   18,  139,    6,    6,

        6,   41,   41,  124,   18,   41,   41,   42,   42,  114,
      104,   42,   42,    6,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,   10,   10,   10,   91,   59,   10,   10,   70,   10,
       70,   70,   70,   70,   10,   10,   10,   10,   10,   10,
       10,   10,   10,   10,   55,   50,   10,   10,   10,   10,
       10,   10,   10,   39,   10,   14,   10,   10,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   19,   19,   19,

       19,   19,   19,   19,   19,   19,   19,   19,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   19,   19,   19,
       19,   19,   19,   19,   19,   20,   20,   20,   20,   20,
       20,   20,   20,   38,   38,   38,   38,   38,   38,   38,
       46,   46,   52,   52,   46,   46,   52,   52,   56,   71,
       71,   72,   72,   71,   71,   72,   72,   90,   90,   90,
       90,   56,   56,   56,   56,   56,   56,   56,   56,   56,
       56,    9,    0,   56,   56,   56,   56,   56,   56,   56,
       57,   57,   57,   57,   57,   57,   57,   57,   58,   58,
       58,   58,   58,   58,   58,   58,   58,   58,   58,   58,

       58,   58,   58,   58,   58,   58,   58,   58,   58,   58,
       58,   58,   58,   58,   58,   58,   58,   58,   58,   58,
       58,   58,   58,   58,   58,   61,   61,   61,   61,   61,
       61,   61,   61,   63,   63,    0,    0,   63,   63,   63,
       63,   63,   63,   63,   80,   95,    0,   95,   95,   95,
       95,  103,  103,  103,  103,    0,    0,   80,   80,   80,
       80,   80,   80,   80,   80,   80,   80,    0,    0,   80,
       80,   80,   80,   80,   80,   80,   83,    0,   83,   83,
       83,   83,   83,   83,   83,   85,   85,   85,   85,   85,
       85,   85,  105,    0,  105,  105,  105,  105,    0,   85,

       86,   86,   86,   86,   86,   86,   86,    0,    0,    0,
       86,   86,   86,   86,   86,   86,   88,    0,   88,   88,
      113,  113,  113,  113,    0,    0,    0,   88,    0,   88,
       89,   89,   89,   89,   89,   89,   89,    0,    0,    0,
       89,   89,   89,   89,   89,   89,   93,    0,   93,   93,
       93,   93,   93,   93,   93,   94,   94,   94,   94,   94,
       94,   94,  115,    0,  115,  115,  115,  115,    0,   94,
       99,   99,   99,   99,   99,   99,   99,    0,    0,    0,
       99,   99,   99,   99,   99,   99,  101,    0,  101,  101,
      123,  123,  123,  123,    0,    0,    0,  101,    0,  101,

      102,  102,  102,  102,  102,  102,  102,    0,    0,    0,
      102,  102,  102,  102,  102,  102,  109,  109,  109,  109,
      109,  109,  109,    0,    0,    0,  109,  109,  109,  109,
      109,  109,  111,    0,  111,  111,    0,    0,    0,    0,
        0,    0,    0,  111,    0,  111,  112,  112,  112,  112,
      112,  112,  112,    0,    0,    0,  112,  112,  112,  112,
      112,  112,  119,  119,  119,  119,  119,  119,  119,    0,
        0,    0,  119,  119,  119,  119,  119,  119,  120,  120,
        0,    0,    0,  120,  120,  120,  120,  121,    0,  121,
      121,    0,    0,    0,    0,    0,    0,    0,  121,    0,

      121,  122,  122,  122,  122,  122,  122,  122,    0,    0,
        0,  122,  122,  122,  122,  122,  122,  129,  129,  129,
      129,  129,  129,  129,  129,  129,  129,  129,  129,  130,
      130,    0,    0,  130,    0,    0,    0,    0,    0,    0,
      130,  131,    0,  131,  132,    0,    0,    0,    0,    0,
        0,    0,  132,  132,  132,  132,  133,    0,    0,    0,
        0,    0,    0,    0,  133,  133,    0,  133,  134,  134,
      134,  134,    0,    0,  134,  135,  135,  135,    0,  135,
      135,  135,  135,  135,  135,  135,  135,  136,    0,  136,
      137,    0,  137,  138,    0,  138,  140,  140,    0,  140,

      141,    0,  141,  142,    0,  142,  143,    0,  143,  144,
        0,  144,  145,    0,  145,  146,    0,  146,  128,  128,
      128,  128,  128,  128,  128,  128,  128,  128,  128,  128,
      128,  128,  128,  128,  128,  128,  128,  128,  128,  128,
      128,  128,  128,  128,  128,  128,  128,  128,  128,  128,
      128,  128,  128,  128,  128,  128
    } ;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#line 1 "ContextOpLexer.lpp"
#define INITIAL 0
/*
 ******************************************************************************
 * ContextOpLexer.lpp : ContextOp lexer
 *
 * Copyright 2001, 2002 Paul Swoboda.
 *
 * This file is part of the Intense project.
 *
 * Intense is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * Intense is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Intense; if not, write to the Free Software Foundation, Inc.,
 * 59 Temple Place, Suite 330, Boston, MA 02111-1307, USA.
 *
 ******************************************************************************
 */
#line 33 "ContextOpLexer.lpp"


#include <list>
#include <map>
#include <string>
#include <sstream>
#include <stdexcept>
#include <stdlib.h>
#include <intense-io.hpp>
#include "IntenseException.hpp"
#include "BoundManager.hpp"
#include "Context.hpp"
#undef contextop_yyFlexLexer
#include "NumberBaseValue.hpp"
#include "StringBaseValue.hpp"
#include "BinaryBaseValue.hpp"
#include "AlphaBaseValue.hpp"
#include "OmegaBaseValue.hpp"
#include "ContextOpLexer.hpp"
#include "StringUtil.hpp"


#define VERSION_YYSTYPE char *
#define LVAL ((Context::Token*)lval)
#define yylex contextop_yylex // flex C++ output screwed...


/* This is the global marker for the input buffer: */
YY_BUFFER_STATE input_buffer;
/* These are just token-position counters: */
int characters, token_characters;


/* The prototype/definition for our definition of the yywrap() routine: */
#define contextop_yywrap() 1


#define IN_STRING 1
#define AFTER_STRING 2
#define IN_BINARY_STRING 3

#line 608 "ContextOpLexer.cpp"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif


#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
#define ECHO LexerOutput( yytext, yyleng )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( (result = LexerInput( (char *) buf, max_size )) < 0 ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) LexerError( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yyFlexLexer::yylex()
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp = NULL, *yy_bp = NULL;
	register int yy_act;

#line 76 "ContextOpLexer.lpp"



#line 739 "ContextOpLexer.cpp"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = &cin;

		if ( ! yyout )
			yyout = &cout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 129 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 719 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 79 "ContextOpLexer.lpp"
{}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 81 "ContextOpLexer.lpp"
{}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 83 "ContextOpLexer.lpp"
{
  switch ((YYText())[1]) {
  case 'n':
    addToString("\n");
    break;
  case 't':
    addToString("\t");
    break;
  case 'v':
    addToString("\v");
    break;
  case 'b':
    addToString("\b");
    break;
  case 'r':
    addToString("\r");
    break;
  case 'f':
    addToString("\f");
    break;
  case 'a':
    addToString("\a");
    break;
  case '\\':
    addToString("\\");
    break;
  case '"':
    addToString("\"");
    break;
  default:
    addToString(&((YYText())[1]));
    break;
  }
  stringBufferRequiresQuotes = true;
  stringBufferIsAllIntChars = false;
}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 120 "ContextOpLexer.lpp"
{
  // Reserved Characters:
  utf8Buffer[StringUtil::utf8EncodeHex(
    utf8Buffer, ((char*)(YYText())) + strlen(YYText()) - 2, 1
  )] = 0;
  addToString(utf8Buffer);
  stringBufferRequiresQuotes = true;
  stringBufferIsAllIntChars = false;
}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 130 "ContextOpLexer.lpp"
{
  utf8Buffer[StringUtil::utf8EncodeHex(
    utf8Buffer, ((char*)(YYText())) + strlen(YYText()) - 2, 1
  )] = 0;
  addToString(utf8Buffer);
}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 137 "ContextOpLexer.lpp"
{
  utf8Buffer[StringUtil::utf8EncodeHex(
    utf8Buffer, ((char*)(YYText())) + 2, 1
  )] = 0;
  addToString(utf8Buffer);
  stringBufferIsAllIntChars = false;
}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 145 "ContextOpLexer.lpp"
{
  utf8Buffer[StringUtil::utf8EncodeHex(
    utf8Buffer, ((char*)(YYText())) + 2, 2
  )] = 0;
  addToString(utf8Buffer);
  stringBufferIsAllIntChars = false;
}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 153 "ContextOpLexer.lpp"
{
  utf8Buffer[StringUtil::utf8EncodeHex(
    utf8Buffer, ((char*)(YYText())) + 2, 3
  )] = 0;
  addToString(utf8Buffer);
  stringBufferIsAllIntChars = false;
}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 161 "ContextOpLexer.lpp"
{
  utf8Buffer[StringUtil::utf8EncodeHex(
    utf8Buffer, ((char*)(YYText())) + 2, 4
  )] = 0;
  addToString(utf8Buffer);
  stringBufferIsAllIntChars = false;
}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 169 "ContextOpLexer.lpp"
{
  return LVAL->setError(*(new string("\\n")));
}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 173 "ContextOpLexer.lpp"
{
  return LVAL->setError(*(new string("\\t")));
}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 177 "ContextOpLexer.lpp"
{
  return LVAL->setError(*(new string("\\v")));
}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 181 "ContextOpLexer.lpp"
{
  return LVAL->setError(*(new string("\\b")));
}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 185 "ContextOpLexer.lpp"
{
  return LVAL->setError(*(new string("\\r")));
}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 189 "ContextOpLexer.lpp"
{
  return LVAL->setError(*(new string("\\f")));
}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 193 "ContextOpLexer.lpp"
{
  return LVAL->setError(*(new string("\\a")));
}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 197 "ContextOpLexer.lpp"
{
  BEGIN(AFTER_STRING);
}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 201 "ContextOpLexer.lpp"
{
  addToString(YYText());
  stringBufferRequiresQuotes = true;
  stringBufferIsAllIntChars = false;
}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 207 "ContextOpLexer.lpp"
{
  addToString(YYText());
}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 211 "ContextOpLexer.lpp"
{
  addToString(YYText());
  stringBufferIsAllIntChars = false;
}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 216 "ContextOpLexer.lpp"
{
  continue;
}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 220 "ContextOpLexer.lpp"
{
  BEGIN(IN_STRING); continue;
}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 224 "ContextOpLexer.lpp"
{
  BEGIN(INITIAL);
  return LVAL->setStringDimension(
    stringBuffer.str().data(),
    stringBufferRequiresQuotes||stringBufferIsAllIntChars
  );
}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 232 "ContextOpLexer.lpp"
{
  unput((YYText())[0]);
  BEGIN(INITIAL);
  return LVAL->setBaseValue(
    *(new intense::StringBaseValue(stringBuffer.str().data()))
  );
}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 240 "ContextOpLexer.lpp"
{
  return LVAL->setBaseValue(*(new intense::StringBaseValue("")));
}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 244 "ContextOpLexer.lpp"
{
  stringReset();
  BEGIN(IN_STRING); continue;
}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 249 "ContextOpLexer.lpp"
{
  stringReset();
  BEGIN(IN_BINARY_STRING); continue;
}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 254 "ContextOpLexer.lpp"
{
  addToString((YYText()));
}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 258 "ContextOpLexer.lpp"
{}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 260 "ContextOpLexer.lpp"
{
  unput((YYText())[0]);
  BEGIN(INITIAL);
  return LVAL->setBaseValue(*(stringToBinaryBaseValue()));
}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 266 "ContextOpLexer.lpp"
{
  int value;

  ((char*)YYText())[strlen(YYText()) - 1] = 0;
  value = atol(YYText());
  return LVAL->setIntegerDimension(value);
}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 274 "ContextOpLexer.lpp"
{
  ((char*)YYText())[strlen(YYText()) - 1] = 0;
  return LVAL->setStringDimension(YYText(), false);
}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 279 "ContextOpLexer.lpp"
{
  double value;

  unput((YYText())[strlen(YYText()) - 1]);
  ((char*)YYText())[strlen(YYText()) - 1] = 0;
  value = strtod(YYText(), NULL);
  return LVAL->setBaseValue(*(new NumberBaseValue(value)));
}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 288 "ContextOpLexer.lpp"
{
  return LVAL->setBaseValue(*(new StringBaseValue(YYText())));
}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 292 "ContextOpLexer.lpp"
{
  return LVAL->setBaseValue(*(new AlphaBaseValue()));
}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 296 "ContextOpLexer.lpp"
{
  return LVAL->setBaseValue(*(new OmegaBaseValue()));
}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 300 "ContextOpLexer.lpp"
{
  return LVAL->setDash();
}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 304 "ContextOpLexer.lpp"
{
  return LVAL->setDashDash();
}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 308 "ContextOpLexer.lpp"
{
  return LVAL->setDashDashDash();
}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 312 "ContextOpLexer.lpp"
{
  return LVAL->setLAngle();
}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 316 "ContextOpLexer.lpp"
{
  return LVAL->setRAngle();
}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 320 "ContextOpLexer.lpp"
{
  return LVAL->setLSquare();
}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 324 "ContextOpLexer.lpp"
{
  return LVAL->setRSquare();
}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 328 "ContextOpLexer.lpp"
{
  return LVAL->setPlus();
}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 332 "ContextOpLexer.lpp"
{
  return LVAL->setError(*(new string(YYText())));
}
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(IN_STRING):
case YY_STATE_EOF(AFTER_STRING):
case YY_STATE_EOF(IN_BINARY_STRING):
#line 336 "ContextOpLexer.lpp"
{
  return LVAL->setEOF();
}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 341 "ContextOpLexer.lpp"
ECHO;
	YY_BREAK
#line 1228 "ContextOpLexer.cpp"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */

yyFlexLexer::yyFlexLexer( istream* arg_yyin, ostream* arg_yyout )
	{
	yyin = arg_yyin;
	yyout = arg_yyout;
	yy_c_buf_p = 0;
	yy_init = 1;
	yy_start = 0;
	yy_flex_debug = 0;
	yylineno = 1;	// this will only get updated if %option yylineno

	yy_did_buffer_switch_on_eof = 0;

	yy_looking_for_trail_begin = 0;
	yy_more_flag = 0;
	yy_more_len = 0;
	yy_more_offset = yy_prev_more_offset = 0;

	yy_start_stack_ptr = yy_start_stack_depth = 0;
	yy_start_stack = 0;

	yy_current_buffer = 0;

#ifdef YY_USES_REJECT
	yy_state_buf = new yy_state_type[YY_BUF_SIZE + 2];
#else
	yy_state_buf = 0;
#endif
	}

yyFlexLexer::~yyFlexLexer()
	{
	delete yy_state_buf;
	yy_delete_buffer( yy_current_buffer );
	}

void yyFlexLexer::switch_streams( istream* new_in, ostream* new_out )
	{
	if ( new_in )
		{
		yy_delete_buffer( yy_current_buffer );
		yy_switch_to_buffer( yy_create_buffer( new_in, YY_BUF_SIZE ) );
		}

	if ( new_out )
		yyout = new_out;
	}

#ifdef YY_INTERACTIVE
int yyFlexLexer::LexerInput( char* buf, int /* max_size */ )
#else
int yyFlexLexer::LexerInput( char* buf, int max_size )
#endif
	{
	if ( yyin->eof() || yyin->fail() )
		return 0;

#ifdef YY_INTERACTIVE
	yyin->get( buf[0] );

	if ( yyin->eof() )
		return 0;

	if ( yyin->bad() )
		return -1;

	return 1;

#else
	(void) yyin->read( buf, max_size );

	if ( yyin->bad() )
		return -1;
	else
		return yyin->gcount();
#endif
	}

void yyFlexLexer::LexerOutput( const char* buf, int size )
	{
	(void) yyout->write( buf, size );
	}

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

int yyFlexLexer::yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

yy_state_type yyFlexLexer::yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 129 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

yy_state_type yyFlexLexer::yy_try_NUL_trans( yy_state_type yy_current_state )
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 129 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 128);

	return yy_is_jam ? 0 : yy_current_state;
	}


void yyFlexLexer::yyunput( int c, register char* yy_bp )
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}


int yyFlexLexer::yyinput()
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


void yyFlexLexer::yyrestart( istream* input_file )
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


void yyFlexLexer::yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


void yyFlexLexer::yy_load_buffer_state()
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


YY_BUFFER_STATE yyFlexLexer::yy_create_buffer( istream* file, int size )
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


void yyFlexLexer::yy_delete_buffer( YY_BUFFER_STATE b )
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


void yyFlexLexer::yy_init_buffer( YY_BUFFER_STATE b, istream* file )

	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

	b->yy_is_interactive = 0;
	}


void yyFlexLexer::yy_flush_buffer( YY_BUFFER_STATE b )
	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#endif


#ifndef YY_NO_SCAN_STRING
#endif


#ifndef YY_NO_SCAN_BYTES
#endif


#ifndef YY_NO_PUSH_STATE
void yyFlexLexer::yy_push_state( int new_state )
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
void yyFlexLexer::yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
int yyFlexLexer::yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif


void yyFlexLexer::LexerError( yyconst char msg[] )
	{
	cerr << msg << '\n';
	exit( YY_EXIT_FAILURE );
	}


/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 341 "ContextOpLexer.lpp"



intense::ContextOpLexer::ContextOpLexer
(istream& is)
  : yyFlexLexer(&is), stringBuffer(), stringBufferRequiresQuotes(false),
    stringBufferIsAllIntChars(true)
{}


intense::ContextOpLexer::~ContextOpLexer
()
{}


// Turn a # hex string into a BinaryBaseValue.
// We are relying on the rules above to give us an even number of characters
// in the range [0-9a-fA-F] (which is reasonable):
intense::BinaryBaseValue* intense::ContextOpLexer::stringToBinaryBaseValue
()
{
  string binaryString = stringBuffer.str();
  BinaryBaseValue* value = new BinaryBaseValue(binaryString.length()/2);
  int bytesWritten = StringUtil::hexStringToBinaryString(
    (char*)(value->content), binaryString.data(), binaryString.length()/2
  );

  if (bytesWritten != binaryString.length()/2) {
    throw IntenseException(
      "INTERNAL ERROR: Invalid byte count in hex conversion"
    );
  }
  return value;
}
